## Load Data

In [ ]:
# Import Library
import pandas as pd

In [4]:
# Menampilkan dan Membaca Data
df_buah = pd.read_csv('citrus.csv')
df_buah.head()

     name  diameter  weight  red  green  blue
0  orange      2.96   86.76  172     85     2
1  orange      3.91   88.05  166     78     3
2  orange      4.42   95.17  156     81     2
3  orange      4.47   95.60  163     81     4
4  orange      4.48   95.76  161     72     9

In [7]:
# Menampilkan Info
df_buah.info()

# Menampilkan Describe
df_buah.describe().round(2)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   name      10000 non-null  object
 1   diameter  10000 non-null  float64
 2   weight    10000 non-null  float64
 3   red       10000 non-null  int64
 4   green     10000 non-null  int64
 5   blue      10000 non-null  int64
dtypes: float64(2), int64(3), object(1)
memory usage: 468.9+ KB

       diameter    weight       red     green      blue
count  10000.00  10000.00  10000.00  10000.00  10000.00
mean       9.98    175.05    153.85     76.01     11.36
std        1.95     29.21     10.43     11.71      9.06
min        2.96     86.76    115.00     31.00      2.00
25%        8.46    152.22    147.00     68.00      2.00
50%        9.98    174.98    154.00     76.00     10.00
75%       11.48    197.72    161.00     84.00     17.00
max       16.45    261.51    192.00    116.00     56.00

In [8]:
# Melihat Jumlah Duplikat
print(f'Jumlah Duplikat : {df_buah.duplicated().sum()}')

Jumlah Duplikat : 0

## Encoding Label

In [ ]:
# Import Library
from sklearn.preprocessing import LabelEncoder

# Encoding Label Target
le = LabelEncoder()
df_buah['name'] = le.fit_transform(df_buah['name'])

df_buah.head()

   name  diameter  weight  red  green  blue
0     1      2.96   86.76  172     85     2
1     1      3.91   88.05  166     78     3
2     1      4.42   95.17  156     81     2
3     1      4.47   95.60  163     81     4
4     1      4.48   95.76  161     72     9

In [10]:
# Mapping label
label_mapping = dict(zip(le.classes_, le.transform(le.classes_)))
print('Mapping Label:', label_mapping)

Mapping Label: {'grapefruit': 0, 'orange': 1}

## Visualisasi Data

In [ ]:
# Import Library
import seaborn as sns
import matplotlib.pyplot as plt
import math

In [ ]:
# Menentukan Jumlah Baris dan Kolom
jumlah_kolom = 3
jumlah_baris = math.ceil(len(df_buah.columns) / jumlah_kolom)

# Membuat Canvas
fig, ax = plt.subplots(jumlah_baris, jumlah_kolom, figsize=(10, jumlah_baris * 2))
ax=ax.flatten()

# Looping Visualisasi
for i, kolom in enumerate(df_buah.columns) : 
    sns.histplot(data=df_buah, x=kolom, ax=ax[i])
    ax[i].set_title(f'Sebaran Data {kolom}')

# Menampilkan Visualisasi
plt.tight_layout()
plt.show()